# --- !Ups
CREATE TABLE ORDERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CLIENT_ID BIGINT NOT NULL,
    ITEM_TYPE NUMBER NOT_NULL,
    ITEM_TAG VARCHAR NOT_NULL,
    BID_PX MONEY
);


# --- !Downs

DROP TABLE ORDERS;